== Opgaver til modul 7

=== Opgave 4

Given a taskset:T1=50,c1=20,d1=60,T2=80,c2=20,d2=50(mS)

. Does utilization guarantee feasibility of an RMA schedule ?
. Validate an RMA schedule with the exact schedulability criterion.
. What is the optimal fixed priority schedule ?
. Validate the optimal fixed priority schedule with the exact
schedulability criterion.

==== Løsning

____
_Does utilization guarantee feasibility of an RMA schedule?_
____


Først regner jeg utilization ud.

----
U = 20/50 + 20/80 = 0.65
----

Derefter kan man regne utilization critereon ud.

----
\overline{U} = 2 * (2^(1/2) - 1) = 0.82
----

Her kan man garantere at RMA er schedulable.

____
_Validate an RMA schedule with the exact schedulability criterion._
____

Her sætter jeg bægge til at starte på samme tid og tester hver.

----
i   T0  T1  R0  R1  D0  D1       i   T0  T1  R0  R1  D0  D1
0   |       19  20  60  50       0   |       19  20  60  50
1   |       18  20  59  49       1   |       18  20  59  49
2   |       17  20  58  48       2   |       17  20  58  48
3   |       16  20  57  47       3   |       16  20  57  47
4   |       15  20  56  46       4   |       15  20  56  46
5   |       14  20  55  45       5   |       14  20  55  45
6   |       13  20  54  44       6   |       13  20  54  44
7   |       12  20  53  43       7   |       12  20  53  43
8   |       11  20  52  42       8   |       11  20  52  42
9   |       10  20  51  41       9   |       10  20  51  41
10  |       9   20  50  40       10  |       9   20  50  40
11  |       8   20  49  39       11  |       8   20  49  39
12  |       7   20  48  38       12  |       7   20  48  38
13  |       6   20  47  37       13  |       6   20  47  37
14  |       5   20  46  36       14  |       5   20  46  36
15  |       4   20  45  35       15  |       4   20  45  35
16  |       3   20  44  34       16  |       3   20  44  34
17  |       2   20  43  33       17  |       2   20  43  33
18  |       1   20  42  32       18  |       1   20  42  32
19  |       0   20  41  31       19  |       0   20  41  31
                                 20      |   0   19  40  30
                                 21      |   0   18  39  29
                                 22      |   0   17  38  28
                                 23      |   0   16  37  27
                                 24      |   0   15  36  26
                                 25      |   0   14  35  25
                                 26      |   0   13  34  24
                                 27      |   0   12  33  23
                                 28      |   0   11  32  22
                                 29      |   0   10  31  21
                                 30      |   0   9   30  20
                                 31      |   0   8   29  19
                                 32      |   0   7   28  18
                                 33      |   0   6   27  17
                                 34      |   0   5   26  16
                                 35      |   0   4   25  15
                                 36      |   0   3   24  14
                                 37      |   0   2   23  13
                                 38      |   0   1   22  12
                                 39      |   0   0   21  11
----

Her kan man se at de begge bliver completed.

____
_What is the optimal fixed priority schedule ?_
____

Hvis alle deadlines er mindre end periode vil man sige at det er 
